FROM odoo:12.0

RUN whoami
RUN pip3 install pandas
RUN pip3 install zxcvbn
RUN pip3 install ptpython
RUN pip3 install email_validator


USER root
RUN pip3 install pandas
RUN pip3 install zxcvbn
RUN pip3 install odooly
RUN pip3 install wdb.server
RUN pip3 install wdb
RUN pip3 install ptpython
RUN pip3 install email_validator

